<a href="https://colab.research.google.com/github/abdrhmnre/Abdrhmnre/blob/main/PYTORCH1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


2.5.1+cu124


In [ ]:
#scaler
#tensor
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector=torch.tensor([7,7])
vector
matrix=torch.tensor([[7,8],[9,10]])
matrix
TENSOR=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR.ndim

3

In [ ]:
TENSOR=torch.tensor([[[1,2,3,]
                      ,[3,6,9,]
                      ,[2,4,5,],
                       [2,4,5,]]])
TENSOR.shape
TENSOR.ndim


3

In [ ]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [2, 4, 5]]])

In [ ]:
random_tensor=torch.rand(1,4,5)
random_tensor

tensor([[[0.2082, 0.4989, 0.8302, 0.9117, 0.2007],
         [0.1943, 0.2437, 0.6377, 0.3021, 0.3896],
         [0.3157, 0.2136, 0.4869, 0.7254, 0.7838],
         [0.1537, 0.0673, 0.7206, 0.0491, 0.5629]]])

In [ ]:
#creating range using torch.range(star,end,step)
apple=torch.range(1,211,3)
apple


<ipython-input-7-69b4c77bfc1d>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  apple=torch.range(1,211,3)


tensor([  1.,   4.,   7.,  10.,  13.,  16.,  19.,  22.,  25.,  28.,  31.,  34.,
         37.,  40.,  43.,  46.,  49.,  52.,  55.,  58.,  61.,  64.,  67.,  70.,
         73.,  76.,  79.,  82.,  85.,  88.,  91.,  94.,  97., 100., 103., 106.,
        109., 112., 115., 118., 121., 124., 127., 130., 133., 136., 139., 142.,
        145., 148., 151., 154., 157., 160., 163., 166., 169., 172., 175., 178.,
        181., 184., 187., 190., 193., 196., 199., 202., 205., 208., 211.])

In [ ]:
#creating tensors like to create shape like something but with zeros
zero_like=torch.zeros_like(input=apple)
zero_like

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#tensor datatype
#tensor dtype is one of three errors you will run into with pytorch & deep learnning
# 1- tensor is not in the right dtype 2- tensor is not in the right shape
#3- tensor is not in the right device
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)

float32=torch.tensor([6.0,6.0,9.0],dtype=torch.int32,device=None,requires_grad=False)

#gradiant to track gradiants with tensors oprations
float32*float_32_tensor

tensor([18., 36., 81.])

In [ ]:
#create a rando tensor
tensor12=torch.rand(3,4)
tensor12

tensor([[0.8705, 0.9264, 0.3774, 0.7113],
        [0.8576, 0.6219, 0.4738, 0.4918],
        [0.8579, 0.7147, 0.0405, 0.5627]])

In [ ]:
tensor=torch.tensor([1,6,12])
tensor + 12
tensor

tensor([ 1,  6, 12])

In [ ]:
#torch . mm = torch.matmul

torch.matmul(tensor,tensor)

tensor(181)

In [ ]:
new=torch.rand(10,5)
new.shape

torch.Size([10, 5])

In [ ]:
torch.matmul(new,torch.transpose(new, 0, 1))

tensor([[1.2821, 0.9890, 0.9108, 1.2246, 1.0023, 1.5215, 1.2366, 1.0733, 1.0798,
         1.1943],
        [0.9890, 1.3804, 0.6291, 1.0128, 1.2721, 1.4654, 1.6937, 1.4682, 0.7158,
         1.0390],
        [0.9108, 0.6291, 1.0893, 1.2981, 0.8199, 0.8790, 0.6354, 0.7433, 1.2912,
         1.0829],
        [1.2246, 1.0128, 1.2981, 1.7390, 1.4238, 1.5042, 1.0778, 1.1400, 1.7077,
         1.4738],
        [1.0023, 1.2721, 0.8199, 1.4238, 1.7867, 1.6999, 1.3697, 1.3163, 1.2754,
         1.1055],
        [1.5215, 1.4654, 0.8790, 1.5042, 1.6999, 2.3104, 1.8772, 1.5546, 1.3084,
         1.5748],
        [1.2366, 1.6937, 0.6354, 1.0778, 1.3697, 1.8772, 2.2525, 1.8365, 0.7047,
         1.4143],
        [1.0733, 1.4682, 0.7433, 1.1400, 1.3163, 1.5546, 1.8365, 1.5952, 0.8433,
         1.2518],
        [1.0798, 0.7158, 1.2912, 1.7077, 1.2754, 1.3084, 0.7047, 0.8433, 1.7909,
         1.4326],
        [1.1943, 1.0390, 1.0829, 1.4738, 1.1055, 1.5748, 1.4143, 1.2518, 1.4326,
         1.7794]])

In [ ]:
#shapes for matix muliplication
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
tensor_B=torch.tensor([[7,10],[8,11],[9,12]])
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.transpose(new, 0, 1)

tensor([[0.1605, 0.2384, 0.6128],
        [0.7233, 0.7395, 0.3976]])

In [ ]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
x= torch.arange(5,200,10)
x

tensor([  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105, 115, 125, 135,
        145, 155, 165, 175, 185, 195])

In [ ]:
torch.min(x)

tensor(5)

In [5]:
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))